# GLPI persistent data
glpidata:
  image: ubuntu
  volumes:
    - /var/www/html/glpi

# GLPI container
glpi:
  image: driket54/glpi
  ports:
    - "8090:80"
  links:
    - mysql:db
  env_file:
    - ./glpi.env
  volumes_from:
    - glpidata

# Database persistent data
mysqldata:
  image: ubuntu
  volumes:
    - /var/lib/mysql

# Database container
mysql:
  image: mariadb
  env_file:
    - ./glpi.env
  volumes_from:
    - mysqldata
